
name: CI Deploy

on:
  push:
      branches:
        - main
        - master
jobs:
  deploy:
    runs-on: ubuntu1-latest
    env:
      SSH_KEY: ${{ secrets.TOP_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        pip install -r requirements.txt

      - name: finish
        run: |
          echo "Amazing!"
